language: node_js
node_js:
  - '14'
  - '13'
  - '12'
  - '10'
  - '8'
cache:
  npm: true
install:
  - npm install
script:
  - npm run lint
  - npm test
os:
  - 'linux'
  - 'osx'
  - 'windows'
after_success: npm run coverage
