name: Joitor Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [12.x, 14.x, 16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }} in ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node: ${{ matrix.node }}
      - run: npm ci
      - run: npm run lint
      - run: npm test

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with: 
        node: 16.x
    - name: Run the tests
      run: |
        npm ci
        npm run coverage
      env:
        CI: true
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
